ALTER TABLE contratos
    MODIFY COLUMN status ENUM(
        'RASCUNHO',
        'ENVIADO_CLICKSIGN',
        'AGUARDANDO_ASSINATURA',
        'ENCAMINHADO_PROJETO',
        'CONCLUIDO',
        'EM_ELABORACAO',
        'ATIVO',
        'EM_IMPLANTACAO',
        'SUSPENSO',
        'ENCERRADO',
        'CANCELADO'
    ) NOT NULL DEFAULT 'RASCUNHO',
    ADD COLUMN contato_nome VARCHAR(150) NULL AFTER cliente_id,
    ADD COLUMN contato_email VARCHAR(150) NULL AFTER contato_nome,
    ADD COLUMN contato_telefone VARCHAR(40) NULL AFTER contato_email,
    ADD COLUMN data_fechamento DATE NULL AFTER fim_vigencia,
    ADD COLUMN executivo_id BIGINT NULL AFTER data_fechamento,
    ADD COLUMN parceiro_id BIGINT NULL AFTER executivo_id,
    ADD COLUMN tipo_venda VARCHAR(30) NULL AFTER parceiro_id,
    ADD COLUMN valor_setup DECIMAL(15,2) NULL AFTER valor_mensal,
    ADD COLUMN valor_projeto DECIMAL(15,2) NULL AFTER valor_setup,
    ADD COLUMN valor_promocional DECIMAL(15,2) NULL AFTER valor_projeto,
    ADD COLUMN quantidade_usuarios INT NULL AFTER valor_promocional,
    ADD COLUMN data_inicio_recorrencia DATE NULL AFTER quantidade_usuarios,
    ADD COLUMN data_ativacao DATE NULL AFTER data_inicio_recorrencia,
    ADD COLUMN arquivo_preparado VARCHAR(255) NULL AFTER observacoes,
    ADD COLUMN arquivo_preparado_original VARCHAR(255) NULL AFTER arquivo_preparado,
    ADD COLUMN arquivo_assinado VARCHAR(255) NULL AFTER arquivo_preparado_original,
    ADD COLUMN arquivo_assinado_original VARCHAR(255) NULL AFTER arquivo_assinado,
    ADD COLUMN clicksign_status VARCHAR(40) NOT NULL DEFAULT 'NAO_ENVIADO' AFTER arquivo_assinado_original,
    ADD COLUMN clicksign_document_key VARCHAR(120) NULL AFTER clicksign_status,
    ADD COLUMN clicksign_envelope_id VARCHAR(120) NULL AFTER clicksign_document_key,
    ADD COLUMN clicksign_enviado_em DATETIME NULL AFTER clicksign_envelope_id,
    ADD COLUMN clicksign_assinado_em DATETIME NULL AFTER clicksign_enviado_em,
    ADD INDEX idx_contratos_data_fechamento (data_fechamento),
    ADD INDEX idx_contratos_executivo_id (executivo_id),
    ADD INDEX idx_contratos_parceiro_id (parceiro_id),
    ADD INDEX idx_contratos_clicksign_status (clicksign_status);
