CREATE TABLE IF NOT EXISTS o3web_licencas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    chave_ativacao VARCHAR(80) NULL,
    id_licenca VARCHAR(40) NULL,
    tipo VARCHAR(40) NULL,
    bkp TINYINT(1) NOT NULL DEFAULT 0,
    dias INT NULL,
    usuarios INT NULL,
    edicao VARCHAR(80) NULL,
    data_ativacao DATETIME NULL,
    data_ativacao_raw VARCHAR(40) NULL,
    data_expiracao DATETIME NULL,
    data_expiracao_raw VARCHAR(40) NULL,
    cliente_nome VARCHAR(180) NOT NULL,
    url_principal VARCHAR(255) NULL,
    url_secundaria VARCHAR(255) NULL,
    comments TEXT NULL,
    observacao TEXT NULL,
    origem VARCHAR(40) NOT NULL DEFAULT 'CSV',
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_o3web_licencas_id_licenca (id_licenca),
    KEY idx_o3web_licencas_chave (chave_ativacao),
    KEY idx_o3web_licencas_cliente (cliente_nome),
    KEY idx_o3web_licencas_tipo (tipo),
    KEY idx_o3web_licencas_expiracao (data_expiracao),
    KEY idx_o3web_licencas_ativo (ativo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
