CREATE TABLE IF NOT EXISTS implantacao_integracoes_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    tipo VARCHAR(30) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    base_url VARCHAR(255) NOT NULL,
    usuario VARCHAR(150) NULL,
    token_nome VARCHAR(150) NULL,
    segredo_encrypted TEXT NULL,
    verify_ssl TINYINT(1) NOT NULL DEFAULT 1,
    timeout_seconds INT NOT NULL DEFAULT 30,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    observacoes TEXT NULL,
    ultimo_teste_status VARCHAR(40) NULL,
    ultimo_teste_mensagem TEXT NULL,
    ultimo_teste_em DATETIME NULL,
    created_by VARCHAR(150) NULL,
    updated_by VARCHAR(150) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_implantacao_integracoes_tipo_nome (tipo, nome),
    KEY idx_implantacao_integracoes_tipo_ativo (tipo, ativo),
    KEY idx_implantacao_integracoes_ultimo_teste (ultimo_teste_status, ultimo_teste_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
