CREATE TABLE IF NOT EXISTS financeiro_recebimentos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    codigo_externo BIGINT NOT NULL,
    cliente_id BIGINT NULL,
    contrato_id BIGINT NULL,
    numero_documento VARCHAR(60) NULL,
    numero_documento_fiscal VARCHAR(60) NULL,
    numero_parcela VARCHAR(20) NULL,
    numero_contrato VARCHAR(50) NULL,
    categoria_codigo VARCHAR(30) NULL,
    categoria_nome VARCHAR(180) NULL,
    categoria_excluida TINYINT(1) NOT NULL DEFAULT 0,
    motivo_exclusao VARCHAR(180) NULL,
    valor_original DECIMAL(15,2) NULL,
    valor_recebido DECIMAL(15,2) NULL,
    valor_desconto DECIMAL(15,2) NULL,
    valor_juros DECIMAL(15,2) NULL,
    data_vencimento DATE NULL,
    data_recebimento DATE NULL,
    data_emissao DATE NULL,
    situacao VARCHAR(40) NULL,
    codigo_cliente_omie BIGINT NULL,
    codigo_contrato_omie BIGINT NULL,
    codigo_vendedor BIGINT NULL,
    codigo_projeto BIGINT NULL,
    origem VARCHAR(20) NOT NULL DEFAULT 'OMIE',
    synced_at DATETIME NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_financeiro_recebimentos_codigo_externo (codigo_externo),
    KEY idx_financeiro_recebimentos_cliente (cliente_id),
    KEY idx_financeiro_recebimentos_contrato (contrato_id),
    KEY idx_financeiro_recebimentos_numero_contrato (numero_contrato),
    KEY idx_financeiro_recebimentos_situacao (situacao),
    KEY idx_financeiro_recebimentos_data_recebimento (data_recebimento),
    KEY idx_financeiro_recebimentos_categoria_excluida (categoria_excluida),
    CONSTRAINT fk_financeiro_recebimentos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_financeiro_recebimentos_contrato FOREIGN KEY (contrato_id) REFERENCES contratos(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
