CREATE TABLE IF NOT EXISTS crm_sucesso_cliente_pesquisas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    token CHAR(36) NOT NULL UNIQUE,
    contrato_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    destinatario_email VARCHAR(180) NOT NULL,
    perguntas_json JSON NOT NULL,
    status ENUM('RASCUNHO','ENVIADA','RESPONDIDA') NOT NULL DEFAULT 'RASCUNHO',
    email_enviado TINYINT(1) NOT NULL DEFAULT 0,
    email_resultado VARCHAR(500) NULL,
    enviado_em DATETIME NULL,
    respondido_em DATETIME NULL,
    resposta_nome VARCHAR(150) NULL,
    resposta_email VARCHAR(180) NULL,
    respostas_json JSON NULL,
    media_nota DECIMAL(4,2) NULL,
    classificacao_nota TINYINT NULL,
    arquivo_resposta VARCHAR(500) NULL,
    created_by VARCHAR(120) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_cs_pesquisa_contrato (contrato_id, created_at),
    KEY idx_cs_pesquisa_status (status),
    KEY idx_cs_pesquisa_classificacao (classificacao_nota),
    CONSTRAINT fk_cs_pesquisa_contrato FOREIGN KEY (contrato_id) REFERENCES contratos(id),
    CONSTRAINT fk_cs_pesquisa_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
