CREATE TABLE IF NOT EXISTS contratos_adendos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    contrato_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    tipo VARCHAR(40) NOT NULL DEFAULT 'OUTRO',
    titulo VARCHAR(160) NOT NULL,
    numero_adendo VARCHAR(80) NULL,
    data_adendo DATE NULL,
    valor_recorrente DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_pontual DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    quantidade_usuarios INT NULL,
    observacoes TEXT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    created_by VARCHAR(180) NULL,
    updated_by VARCHAR(180) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_contratos_adendos_contrato (contrato_id, ativo),
    KEY idx_contratos_adendos_cliente (cliente_id, ativo),
    CONSTRAINT fk_contratos_adendos_contrato FOREIGN KEY (contrato_id) REFERENCES contratos(id),
    CONSTRAINT fk_contratos_adendos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contratos_adendos_anexos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    adendo_id BIGINT NOT NULL,
    arquivo VARCHAR(255) NOT NULL,
    arquivo_original VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NULL,
    tamanho BIGINT NULL,
    uploaded_by VARCHAR(180) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    KEY idx_contratos_adendos_anexos_adendo (adendo_id, created_at),
    CONSTRAINT fk_contratos_adendos_anexos_adendo FOREIGN KEY (adendo_id) REFERENCES contratos_adendos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS financeiro_premiacoes_adendos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL UNIQUE,
    adendo_id BIGINT NOT NULL,
    contrato_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    campanha_id BIGINT NULL,
    parceiro_id BIGINT NULL,
    executivo_id BIGINT NULL,
    descricao VARCHAR(255) NOT NULL,
    data_lancamento DATE NOT NULL,
    valor_base DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    percentual_parceiro DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
    percentual_executivo DECIMAL(7,4) NOT NULL DEFAULT 0.0000,
    valor_premiacao_parceiro DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_premiacao_executivo DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    valor_total DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    status_manual VARCHAR(30) NOT NULL DEFAULT 'ABERTO',
    observacoes TEXT NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    created_by VARCHAR(180) NULL,
    updated_by VARCHAR(180) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_financeiro_premiacoes_adendos_adendo (adendo_id, ativo),
    KEY idx_financeiro_premiacoes_adendos_contrato (contrato_id, ativo),
    KEY idx_financeiro_premiacoes_adendos_campanha (campanha_id),
    KEY idx_financeiro_premiacoes_adendos_status (status_manual),
    CONSTRAINT fk_financeiro_premiacoes_adendos_adendo FOREIGN KEY (adendo_id) REFERENCES contratos_adendos(id),
    CONSTRAINT fk_financeiro_premiacoes_adendos_contrato FOREIGN KEY (contrato_id) REFERENCES contratos(id),
    CONSTRAINT fk_financeiro_premiacoes_adendos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_financeiro_premiacoes_adendos_campanha FOREIGN KEY (campanha_id) REFERENCES regras_campanhas_comissao(id),
    CONSTRAINT fk_financeiro_premiacoes_adendos_parceiro FOREIGN KEY (parceiro_id) REFERENCES parceiros(id),
    CONSTRAINT fk_financeiro_premiacoes_adendos_executivo FOREIGN KEY (executivo_id) REFERENCES parceiros_executivos(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
